perl downloadGenomes.pl refseqGenomeInformation.txt
perl downloadProteomes.pl refseqGenomeInformation.txt
perl downloadGenomes.pl refseqGenomeInformation.txt
perl downloadProteomes.pl refseqGenomeInformation.txt